name: 'IBM Cloud Login'
description: 'Use this action to login to IBM Cloud'
inputs:
  ibm-cloud-api-key:  # api-key
    description: 'IBM Cloud API Key'
    required: true
  ibm-cloud-region: # region to log into
    description: 'IBM Cloud Region'
    required: true
  ibm-cloud-org: # organization to log into
    description: 'IBM Cloud Organization'
    required: true
  ibm-cloud-space: # space to log into
    description: 'IBM Cloud Space'
    required: true
runs:
  using: "composite"
  steps:
    - id: install-cli
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f cloud-functions
      shell: bash
    - id: cli-login
      run: ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -o "${IBM_CLOUD_ORG}" -s "${IBM_CLOUD_SPACE}"
      shell: bash
      env:
        IBM_CLOUD_API_KEY: ${{ inputs.ibm-cloud-api-key }}
        IBM_CLOUD_REGION: ${{ inputs.ibm-cloud-region }}
        IBM_CLOUD_ORG: ${{ inputs.ibm-cloud-org }}
        IBM_CLOUD_SPACE: ${{ inputs.ibm-cloud-space }}